spring.application.name=app

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_budget_db
spring.datasource.username=smart_budget
spring.datasource.password=S3cret

spring.datasource.driver-class-name=org.postgresql.Driver

# To ensure flyway, not hibernate, manages schema changes:
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.springframework.context.annotation=DEBUG
